name: Deploy FastRoute

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/oliverbill/fastroute-api:latest \
            --push .

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deploy/fastroute

            echo "${{ secrets.GHCR_READ_TOKEN }}" | docker login ghcr.io -u oliverbill --password-stdin

            docker pull ghcr.io/oliverbill/fastroute-api:latest
            docker compose up -d